on:
  push:
    branches:
      - main  # Change 'main' to your default branch name
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: GitHub Action for LW Scanner
    steps:
      - name: Verify LW Account Details
        shell: bash
        run: echo -e "LW_ACCOUNT_NAME:$(echo ${{secrets.LW_ACCOUNT_NAME}} | sed 's/^\(...\)\(.*\)\(...\)$/\1****\3/')\nLW_ACCESS_TOKEN:$(echo ${{secrets.LW_ACCESS_TOKEN}} | sed 's/^\(...\)\(.*\)\(...\)$/\1****\3/')"
      - name: Pull Log4J Vul Container
        shell: bash
        run: |
            docker pull uzyexe/pacman
      - name: Scan container images for vulnerabitilies using Lacework
        uses: lacework/lw-scanner-action@v1.4.0
        continue-on-error: false
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: uzyexe/pacman
          IMAGE_TAG: latest
          SAVE_RESULTS_IN_LACEWORK: true
          SAVE_BUILD_REPORT: true
          BUILD_REPORT_FILE_NAME: report.html
          DEBUGGING: false
          RESULTS_IN_GITHUB_SUMMARY: true

##          FAIL_BUILD: true
#          SEVERITY_THRESHOLD: fixable

#      - name: Check if vulnerabilites were found and step failed.
#        if: steps.lw-scanner.outcome == 'failure'
#        run: echo "Vulnerabilities found and step failed succesfully." && exit 0
