on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: GitHub Action for LW Scanner
    steps:
      - name: Pull The PacMan Container
        shell: bash
        run: |
            docker pull uzyexe/pacman
      - name: Scan container images for vulnerabitilies using Lacework
        uses: timarenz/lw-scanner-action@main
        env:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          LW_SCANNER_SAVE_RESULTS: true
        with:
          image_name: uzyexe/pacman
          image_tag: latest
          fail_if_critical_vulnerabilities_found: true
          fail_only_if_vulnerabilities_fixable: true
          save_build_report: true
