on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
#      - name: Hello world action step
#        id: hello_reesy
#        uses: anthonygrees/lw_container_scanner_demo@v1
#        with:
#          who-to-greet: 'Mona the Octocat'
#        # Use the output from the `hello` step
#      - name: Get the output time
#       run: echo "The time was ${{ steps.hello.outputs.time }}"
#       # Run scanner !
      - name: Pull 
        shell: bash
        run: |
          docker pull nginx:latest 
      - name: Scan container images for vulnerabitilies using Lacework
        uses: timarenz/lw-scanner-action@main
        env:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
        with:
          image_name: nginx
          image_tag: latest
          fail_if_critical_vulnerabilities_found: true
          fail_only_if_vulnerabilities_fixable: true
          save_build_report: true