on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello_reesy
        uses: anthonygrees/lw_container_scanner_demo@v1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Checkout ipcrm/lw-scanner-action
        uses: actions/checkout@v2
        with:
        repository: ipcrm/lw-scanner-action
        ref: refs/heads/main
        path: ./.github/actions/lw-scanner-action

      - 
      uses: ./.github/actions/lw-scanner-action
      name: Scan container images for vulnerabitilies using Lacework
      #     uses: timarenz/lw-scanner-action@v0.2.1
      env:
        LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
        LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
        LW_SCANNER_SCAN_LIBRARY_PACKAGES: true
      with:
        image_name: hello_reesy
        image_tag: latest
        fail_if_critical_vulnerabilities_found: true
        fail_only_if_vulnerabilities_fixable: true
        save_build_report: true